In [1]:
import numpy as np
import pandas as pd

In [ ]:
a = np.arange(10, 51)

In [ ]:
evens = a[a % 2 == 0]

In [ ]:
print(evens)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
identity = np.identity(3)

In [ ]:
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3).flatten()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [ ]:
matrix_5x5 = np.random.rand(5, 5)

In [ ]:
middle_matrix = matrix_5x5[1:4, 1:4]
middle_matrix

array([[0.6272059 , 0.04808344, 0.10770243],
       [0.80938578, 0.38758026, 0.77726228],
       [0.21060846, 0.7599975 , 0.79808232]])

In [ ]:
print(matrix_5x5[:, 0])
print(matrix_5x5[-1, :])

[0.82536107 0.39784399 0.28401851 0.19741514 0.79342496]
[0.79342496 0.89437781 0.95646052 0.26179023 0.17902142]


In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'City': ['New York', 'Los Angeles', 'Chicago']}

In [ ]:
df = pd.DataFrame(data)
df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
np.random.randint(1, 200)

179

In [ ]:
np.random.randint(1, 200, 10)

array([ 34,  27, 115, 111, 187, 193, 120, 196, 125, 137])

In [ ]:
np.full((3, 6), 20)

array([[20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
arr = np.array([1,2,3,4,5])
squared = np.square(arr)
squared

array([ 1,  4,  9, 16, 25])

In [ ]:
filtered_arr = arr[arr > 3]

In [ ]:
filtered_arr

array([4, 5])

In [ ]:
type(filtered_arr)

numpy.ndarray

In [ ]:
np.random.rand(2,2)

array([[0.062205  , 0.48645002],
       [0.18282411, 0.23691585]])

In [ ]:
np.arange(1,200).sum()

19900

In [ ]:
arr.max()

5

In [ ]:
arr.min()

1

In [ ]:
data = { "username": ["user1", "user2", "user3"], "password": ["pass1", "pass2", "pass3"] }

In [ ]:
df = pd.DataFrame(data)
df

username password
0    user1    pass1
1    user2    pass2
2    user3    pass3

In [ ]:
df['username']

0    user1
1    user2
2    user3
Name: username, dtype: object

In [ ]:
df['passwords']

0    pass1
1    pass2
2    pass3
Name: passwords, dtype: object

In [ ]:
df['age'] = [25, 30, 35]

In [ ]:
df

username password  age
0    user1    pass1   25
1    user2    pass2   30
2    user3    pass3   35

In [ ]:
filtered_df = df[df['age'] > 30]

In [ ]:
filtered_df

username password  age
2    user3    pass3   35

In [ ]:
df['age'].mean()

30.0

In [ ]:
len(df)

3

In [ ]:
df.loc[0]

username    user1
password    pass1
age            25
Name: 0, dtype: object

In [ ]:
df.loc[0, ['username', 'password']]

username    user1
password    pass1
Name: 0, dtype: object

In [ ]:
df.iloc[0]

username    user1
password    pass1
age            25
Name: 0, dtype: object

In [ ]:
df.iloc[:, 0:3]

username password  age
0    user1    pass1   25
1    user2    pass2   30
2    user3    pass3   35

In [ ]:
df.iloc[0:2, 0:2]

username password
0    user1    pass1
1    user2    pass2

In [ ]:
df[df['age'] > 25]

username password  age
1    user2    pass2   30
2    user3    pass3   35

In [2]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
arr = np.random.randint(1, 11, (5,5))

In [6]:
arr.mean()

6.12

In [8]:
np.median(arr)

6.0

In [9]:
np.std(arr)

2.56624238917527

In [12]:
np.ones((4,4), dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [13]:
data = { "Name": ["John", "Lucas", "Gabel"], "Age": [25, 30, 35], "City": ["New York", "Los Angeles", "Chicago"] }
df = pd.DataFrame(data)

In [20]:
df.loc[:, ["Name","City"]]
df[['Name', "City"]]

Name         City
0   John     New York
1  Lucas  Los Angeles
2  Gabel      Chicago

In [25]:
df['Salary'] = [50000, 60000, 70000]

In [24]:
df[df['Age'] > 30]

Name  Age     City  salary
2  Gabel   35  Chicago   70000

In [26]:
df['Salary'].mean()

60000.0

In [29]:
df.sort_values("Age", ascending=False)

Name  Age         City  salary  Salary
2  Gabel   35      Chicago   70000   70000
1  Lucas   30  Los Angeles   60000   60000
0   John   25     New York   50000   50000