In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [ ]:
a = np.arange(10, 51)

In [ ]:
evens = a[a % 2 == 0]

In [ ]:
print(evens)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
identity = np.identity(3)

In [ ]:
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3).flatten()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [ ]:
matrix_5x5 = np.random.rand(5, 5)

In [ ]:
middle_matrix = matrix_5x5[1:4, 1:4]
middle_matrix

array([[0.6272059 , 0.04808344, 0.10770243],
       [0.80938578, 0.38758026, 0.77726228],
       [0.21060846, 0.7599975 , 0.79808232]])

In [ ]:
print(matrix_5x5[:, 0])
print(matrix_5x5[-1, :])

[0.82536107 0.39784399 0.28401851 0.19741514 0.79342496]
[0.79342496 0.89437781 0.95646052 0.26179023 0.17902142]


In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'City': ['New York', 'Los Angeles', 'Chicago']}

In [ ]:
df = pd.DataFrame(data)
df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
np.random.randint(1, 200)

179

In [ ]:
np.random.randint(1, 200, 10)

array([ 34,  27, 115, 111, 187, 193, 120, 196, 125, 137])

In [ ]:
np.full((3, 6), 20)

array([[20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
arr = np.array([1,2,3,4,5])
squared = np.square(arr)
squared

array([ 1,  4,  9, 16, 25])

In [ ]:
filtered_arr = arr[arr > 3]

In [ ]:
filtered_arr

array([4, 5])

In [ ]:
type(filtered_arr)

numpy.ndarray

In [ ]:
np.random.rand(2,2)

array([[0.062205  , 0.48645002],
       [0.18282411, 0.23691585]])

In [ ]:
np.arange(1,200).sum()

19900

In [ ]:
arr.max()

5

In [ ]:
arr.min()

1

In [ ]:
data = { "username": ["user1", "user2", "user3"], "password": ["pass1", "pass2", "pass3"] }

In [ ]:
df = pd.DataFrame(data)
df

username password
0    user1    pass1
1    user2    pass2
2    user3    pass3

In [ ]:
df['username']

0    user1
1    user2
2    user3
Name: username, dtype: object

In [ ]:
df['passwords']

0    pass1
1    pass2
2    pass3
Name: passwords, dtype: object

In [ ]:
df['age'] = [25, 30, 35]

In [ ]:
df

username password  age
0    user1    pass1   25
1    user2    pass2   30
2    user3    pass3   35

In [ ]:
filtered_df = df[df['age'] > 30]

In [ ]:
filtered_df

username password  age
2    user3    pass3   35

In [ ]:
df['age'].mean()

30.0

In [ ]:
len(df)

3

In [ ]:
df.loc[0]

username    user1
password    pass1
age            25
Name: 0, dtype: object

In [ ]:
df.loc[0, ['username', 'password']]

username    user1
password    pass1
Name: 0, dtype: object

In [ ]:
df.iloc[0]

username    user1
password    pass1
age            25
Name: 0, dtype: object

In [ ]:
df.iloc[:, 0:3]

username password  age
0    user1    pass1   25
1    user2    pass2   30
2    user3    pass3   35

In [ ]:
df.iloc[0:2, 0:2]

username password
0    user1    pass1
1    user2    pass2

In [ ]:
df[df['age'] > 25]

username password  age
1    user2    pass2   30
2    user3    pass3   35

In [ ]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.random.randint(1, 11, (5,5))

In [ ]:
arr.mean()

6.12

In [ ]:
np.median(arr)

6.0

In [ ]:
np.std(arr)

2.56624238917527

In [ ]:
np.ones((4,4), dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
data = { "Name": ["John", "Lucas", "Gabel"], "Age": [25, 30, 35], "City": ["New York", "Los Angeles", "Chicago"] }
df = pd.DataFrame(data)

In [ ]:
df.loc[:, ["Name","City"]]
df[['Name', "City"]]

Name         City
0   John     New York
1  Lucas  Los Angeles
2  Gabel      Chicago

In [ ]:
df['Salary'] = [50000, 60000, 70000]

In [ ]:
df[df['Age'] > 30]

Name  Age     City  salary
2  Gabel   35  Chicago   70000

In [ ]:
df['Salary'].mean()

60000.0

In [ ]:
df.sort_values("Age", ascending=False)

Name  Age         City  salary  Salary
2  Gabel   35      Chicago   70000   70000
1  Lucas   30  Los Angeles   60000   60000
0   John   25     New York   50000   50000

In [ ]:
np_array = np.arange(1, 10).reshape(3, 3)

In [ ]:
np_array[1, :]

array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
a + b

array([ 4,  6,  8, 10, 12])

In [ ]:
np.arange(1, 13).reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
random_numbers = np.random.randint(1, 101)

In [ ]:
np.mean(random_numbers)

27.0

In [ ]:
np.median(random_numbers)

27.0

In [ ]:
np.std(random_numbers)

0.0

In [ ]:
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)
result

array([[19, 22],
       [43, 50]])

In [ ]:
random_array = np.random.randint(1, 101, size=10)

In [ ]:
filtered_array = random_array[random_array > 50]

In [ ]:
filtered_array

array([77, 95, 56, 93, 59])

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hank", "Ivy", "Jack",
             "Kim", "Liam", "Mona", "Nina", "Owen", "Paul", "Quinn", "Rita", "Sam", "Tina"],
    "Age": [25, 30, 35, 40, 22, 27, 29, 31, 23, 26, 28, 32, 34, 33, 37, 41, 24, 38, 36, 39],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia",
             "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville",
             "Fort Worth", "Columbus", "Charlotte", "San Francisco", "Indianapolis",
             "Seattle", "Denver", "Boston"]
}
df = pd.DataFrame(data)

In [ ]:
df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
df['Salary'] = [50000, 60000, 70000]

In [ ]:
df

Name  Age           City
0     Alice   25       New York
1       Bob   30    Los Angeles
2   Charlie   35        Chicago
3     David   40        Houston
4       Eve   22        Phoenix
5     Frank   27   Philadelphia
6     Grace   29    San Antonio
7      Hank   31      San Diego
8       Ivy   23         Dallas
9      Jack   26       San Jose
10      Kim   28         Austin
11     Liam   32   Jacksonville
12     Mona   34     Fort Worth
13     Nina   33       Columbus
14     Owen   37      Charlotte
15     Paul   41  San Francisco
16    Quinn   24   Indianapolis
17     Rita   38        Seattle
18      Sam   36         Denver
19     Tina   39         Boston

In [ ]:
filtered_df = df[df['Age'] > 30]

In [ ]:
filtered_df

Name  Age           City
2   Charlie   35        Chicago
3     David   40        Houston
7      Hank   31      San Diego
11     Liam   32   Jacksonville
12     Mona   34     Fort Worth
13     Nina   33       Columbus
14     Owen   37      Charlotte
15     Paul   41  San Francisco
17     Rita   38        Seattle
18      Sam   36         Denver
19     Tina   39         Boston

In [ ]:
df.sort_values("Age", ascending=False)

Name  Age           City
15     Paul   41  San Francisco
3     David   40        Houston
19     Tina   39         Boston
17     Rita   38        Seattle
14     Owen   37      Charlotte
18      Sam   36         Denver
2   Charlie   35        Chicago
12     Mona   34     Fort Worth
13     Nina   33       Columbus
11     Liam   32   Jacksonville
7      Hank   31      San Diego
1       Bob   30    Los Angeles
6     Grace   29    San Antonio
10      Kim   28         Austin
5     Frank   27   Philadelphia
9      Jack   26       San Jose
0     Alice   25       New York
16    Quinn   24   Indianapolis
8       Ivy   23         Dallas
4       Eve   22        Phoenix

In [ ]:
df.description()

AttributeError: 'DataFrame' object has no attribute 'description'

In [ ]:
df.describe()

Age
count  20.00000
mean   31.50000
std     5.91608
min    22.00000
25%    26.75000
50%    31.50000
75%    36.25000
max    41.00000

In [ ]:
df.groupby('City')['Age'].mean()

City
Austin           28.0
Boston           39.0
Charlotte        37.0
Chicago          35.0
Columbus         33.0
Dallas           23.0
Denver           36.0
Fort Worth       34.0
Houston          40.0
Indianapolis     24.0
Jacksonville     32.0
Los Angeles      30.0
New York         25.0
Philadelphia     27.0
Phoenix          22.0
San Antonio      29.0
San Diego        31.0
San Francisco    41.0
San Jose         26.0
Seattle          38.0
Name: Age, dtype: float64

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
np_array.shape

(5,)

In [ ]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
b.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
c = np.array([(1,2,3,4), (5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
zeros = np.zeros((5,5), dtype=int)
print(zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full((8,9), 72)

array([[72, 72, 72, 72, 72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72, 72, 72, 72, 72]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(1, 200, (5,5))

array([[179, 195, 171,  46, 151],
       [128,  65, 130,  76,  45],
       [ 16,   2, 171,  30, 105],
       [ 60,  78,  60, 131, 138],
       [ 59, 134,  57, 149, 149]])

In [ ]:
np.random.random((3,5))

array([[0.63993088, 0.361633  , 0.67671498, 0.69415595, 0.16084819],
       [0.80688176, 0.50006986, 0.94593567, 0.74201612, 0.56645341],
       [0.5255879 , 0.64078179, 0.49531876, 0.54252266, 0.96303985]])

In [ ]:
np.linspace(1, 25, 100)

array([ 1.        ,  1.24242424,  1.48484848,  1.72727273,  1.96969697,
        2.21212121,  2.45454545,  2.6969697 ,  2.93939394,  3.18181818,
        3.42424242,  3.66666667,  3.90909091,  4.15151515,  4.39393939,
        4.63636364,  4.87878788,  5.12121212,  5.36363636,  5.60606061,
        5.84848485,  6.09090909,  6.33333333,  6.57575758,  6.81818182,
        7.06060606,  7.3030303 ,  7.54545455,  7.78787879,  8.03030303,
        8.27272727,  8.51515152,  8.75757576,  9.        ,  9.24242424,
        9.48484848,  9.72727273,  9.96969697, 10.21212121, 10.45454545,
       10.6969697 , 10.93939394, 11.18181818, 11.42424242, 11.66666667,
       11.90909091, 12.15151515, 12.39393939, 12.63636364, 12.87878788,
       13.12121212, 13.36363636, 13.60606061, 13.84848485, 14.09090909,
       14.33333333, 14.57575758, 14.81818182, 15.06060606, 15.3030303 ,
       15.54545455, 15.78787879, 16.03030303, 16.27272727, 16.51515152,
       16.75757576, 17.        , 17.24242424, 17.48484848, 17.72

In [ ]:
np.arange(1,30, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
a = np.random.rand(2, 2) * 100
b = np.random.rand(2, 2) * 100
print(a)
print(b)
a+b

[[93.9787464  11.0478312 ]
 [ 1.26157047 70.39173006]]
[[71.46656619 99.64589325]
 [42.38439348 49.125275  ]]


array([[165.44531259, 110.69372445],
       [ 43.64596394, 119.51700506]])

In [30]:
iris_data = load_iris()

In [ ]:
iris_df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
iris_df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [ ]:
iris_df.value_counts("sepal length (cm)")

sepal length (cm)
5.0    10
6.3     9
5.1     9
5.7     8
6.7     8
6.4     7
5.8     7
5.5     7
5.4     6
6.1     6
5.6     6
6.0     6
4.9     6
4.8     5
6.5     5
6.2     4
5.2     4
4.6     4
7.7     4
6.9     4
7.2     3
5.9     3
4.4     3
6.8     3
4.7     2
6.6     2
7.4     1
7.6     1
7.3     1
4.3     1
7.1     1
7.0     1
5.3     1
4.5     1
7.9     1
Name: count, dtype: int64

In [ ]:
iris_df.groupby("sepal length (cm)").mean()

sepal width (cm)  petal length (cm)  petal width (cm)
sepal length (cm)                                                       
4.3                        3.000000           1.100000          0.100000
4.4                        3.033333           1.333333          0.200000
4.5                        2.300000           1.300000          0.300000
4.6                        3.325000           1.325000          0.225000
4.7                        3.200000           1.450000          0.200000
4.8                        3.180000           1.580000          0.200000
4.9                        2.950000           2.266667          0.550000
5.0                        3.120000           1.840000          0.430000
5.1                        3.477778           1.722222          0.400000
5.2                        3.425000           2.075000          0.475000
5.3                        3.700000           1.500000          0.200000
5.4                        3.550000           2.033333          0.516667
5.5                        2.842857           3.228571          0.900000
5.6                        2.816667           4.200000          1.416667
5.7                        3.100000           3.587500          1.100000
5.8                        2.885714           4.071429          1.400000
5.9                        3.066667           4.700000          1.700000
6.0                        2.733333           4.650000          1.500000
6.1                        2.850000           4.750000          1.416667
6.2                        2.825000           4.750000          1.725000
6.3                        2.855556           5.133333          1.811111
6.4                        2.957143           5.157143          1.871429
6.5                        3.000000           5.240000          1.900000
6.6                        2.950000           4.500000          1.350000
6.7                        3.050000           5.262500          1.962500
6.8                        3.000000           5.400000          1.933333
6.9                        3.125000           5.275000          2.050000
7.0                        3.200000           4.700000          1.400000
7.1                        3.000000           5.900000          2.100000
7.2                        3.266667           5.966667          1.966667
7.3                        2.900000           6.300000          1.800000
7.4                        2.800000           6.100000          1.900000
7.6                        3.000000           6.600000          2.100000
7.7                        3.050000           6.600000          2.200000
7.9                        3.800000           6.400000          2.000000

In [ ]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [ ]:
iris_df.count()

sepal length (cm)    150
sepal width (cm)     150
petal length (cm)    150
petal width (cm)     150
dtype: int64

In [ ]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [ ]:
iris_df['Mean'] = iris_df.mean(axis=1)

In [ ]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

    Mean  
0  2.550  
1  2.375  
2  2.350  
3  2.350  
4  2.550

In [ ]:
iris_df.drop('Mean', axis=1, inplace=True)

In [ ]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
iris_df.drop(columns="sepal width (cm)", axis=1, inplace=True)

In [ ]:
iris_df.head()

sepal length (cm)  petal length (cm)  petal width (cm)
0                5.1                1.4               0.2
1                4.9                1.4               0.2
2                4.7                1.3               0.2
3                4.6                1.5               0.2
4                5.0                1.4               0.2

In [ ]:
iris_df.iloc[2:5, 1:2]

petal length (cm)
2                1.3
3                1.5
4                1.4

In [ ]:
iris_df

sepal length (cm)  petal length (cm)  petal width (cm)
0                  5.1                1.4               0.2
1                  4.9                1.4               0.2
2                  4.7                1.3               0.2
3                  4.6                1.5               0.2
4                  5.0                1.4               0.2
..                 ...                ...               ...
145                6.7                5.2               2.3
146                6.3                5.0               1.9
147                6.5                5.2               2.0
148                6.2                5.4               2.3
149                5.9                5.1               1.8

[150 rows x 3 columns]

In [ ]:
iris_df.loc[1: 3, "sepal length (cm)"]

1    4.9
2    4.7
3    4.6
Name: sepal length (cm), dtype: float64

In [3]:
array = [1,2,3,4,5]
type(array)

list

In [4]:
array = np.array(array)
type(array)

numpy.ndarray

In [5]:
 np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
a = np.array([(1,2,3,4,5), (6,7,8,9,10)])

In [9]:
a.shape

(2, 5)

In [11]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.full((5,5), 72)

array([[72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72]])

In [16]:
np.eye(6, dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [17]:
np.random.random((5,5))

array([[0.04088846, 0.49260834, 0.41104463, 0.08549177, 0.5722906 ],
       [0.12870913, 0.07810129, 0.22521249, 0.55200702, 0.13711298],
       [0.74083316, 0.14226932, 0.55218407, 0.52386241, 0.33575317],
       [0.0467203 , 0.16815854, 0.04657323, 0.34413097, 0.11100248],
       [0.52793463, 0.94173098, 0.80281368, 0.80430174, 0.22070356]])

In [18]:
np.random.randint(1, 200, (5,5))

array([[ 18,  58,  94,  98, 113],
       [ 67, 173,  11,  54,  78],
       [ 35, 142, 102,  39,  21],
       [105,  75,  32,  30, 117],
       [ 32, 111, 158, 182,  88]])

In [21]:
np.random.rand(3,2)

array([[0.46923686, 0.02888953],
       [0.56087181, 0.82474029],
       [0.19739074, 0.95997146]])

In [22]:
np.linspace(1, 25, 100)

array([ 1.        ,  1.24242424,  1.48484848,  1.72727273,  1.96969697,
        2.21212121,  2.45454545,  2.6969697 ,  2.93939394,  3.18181818,
        3.42424242,  3.66666667,  3.90909091,  4.15151515,  4.39393939,
        4.63636364,  4.87878788,  5.12121212,  5.36363636,  5.60606061,
        5.84848485,  6.09090909,  6.33333333,  6.57575758,  6.81818182,
        7.06060606,  7.3030303 ,  7.54545455,  7.78787879,  8.03030303,
        8.27272727,  8.51515152,  8.75757576,  9.        ,  9.24242424,
        9.48484848,  9.72727273,  9.96969697, 10.21212121, 10.45454545,
       10.6969697 , 10.93939394, 11.18181818, 11.42424242, 11.66666667,
       11.90909091, 12.15151515, 12.39393939, 12.63636364, 12.87878788,
       13.12121212, 13.36363636, 13.60606061, 13.84848485, 14.09090909,
       14.33333333, 14.57575758, 14.81818182, 15.06060606, 15.3030303 ,
       15.54545455, 15.78787879, 16.03030303, 16.27272727, 16.51515152,
       16.75757576, 17.        , 17.24242424, 17.48484848, 17.72

In [23]:
np.arange(1,200)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [24]:
np.arange(1, 200, 2)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199])

In [25]:
a.ndim

2

In [28]:
a = np.random.randint(1, 200, (2,2),dtype=int)
b = np.random.randint(1, 200, (2,2),dtype=int)
print(a)
print(b)

[[ 34 120]
 [199  52]]
[[156  39]
 [176   4]]


In [29]:
a + b

array([[190, 159],
       [375,  56]])

In [31]:
iris_df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)

In [32]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [33]:
iris_df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [34]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [35]:
iris_df.shape

(150, 4)

In [36]:
iris_df.ndim

2

In [38]:
iris_df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [39]:
iris_df.value_counts("sepal length (cm)")

sepal length (cm)
5.0    10
6.3     9
5.1     9
5.7     8
6.7     8
6.4     7
5.8     7
5.5     7
5.4     6
6.1     6
5.6     6
6.0     6
4.9     6
4.8     5
6.5     5
6.2     4
5.2     4
4.6     4
7.7     4
6.9     4
7.2     3
5.9     3
4.4     3
6.8     3
4.7     2
6.6     2
7.4     1
7.6     1
7.3     1
4.3     1
7.1     1
7.0     1
5.3     1
4.5     1
7.9     1
Name: count, dtype: int64

In [40]:
iris_df.groupby("sepal length (cm)").mean()

sepal width (cm)  petal length (cm)  petal width (cm)
sepal length (cm)                                                       
4.3                        3.000000           1.100000          0.100000
4.4                        3.033333           1.333333          0.200000
4.5                        2.300000           1.300000          0.300000
4.6                        3.325000           1.325000          0.225000
4.7                        3.200000           1.450000          0.200000
4.8                        3.180000           1.580000          0.200000
4.9                        2.950000           2.266667          0.550000
5.0                        3.120000           1.840000          0.430000
5.1                        3.477778           1.722222          0.400000
5.2                        3.425000           2.075000          0.475000
5.3                        3.700000           1.500000          0.200000
5.4                        3.550000           2.033333          0.516667
5.5                        2.842857           3.228571          0.900000
5.6                        2.816667           4.200000          1.416667
5.7                        3.100000           3.587500          1.100000
5.8                        2.885714           4.071429          1.400000
5.9                        3.066667           4.700000          1.700000
6.0                        2.733333           4.650000          1.500000
6.1                        2.850000           4.750000          1.416667
6.2                        2.825000           4.750000          1.725000
6.3                        2.855556           5.133333          1.811111
6.4                        2.957143           5.157143          1.871429
6.5                        3.000000           5.240000          1.900000
6.6                        2.950000           4.500000          1.350000
6.7                        3.050000           5.262500          1.962500
6.8                        3.000000           5.400000          1.933333
6.9                        3.125000           5.275000          2.050000
7.0                        3.200000           4.700000          1.400000
7.1                        3.000000           5.900000          2.100000
7.2                        3.266667           5.966667          1.966667
7.3                        2.900000           6.300000          1.800000
7.4                        2.800000           6.100000          1.900000
7.6                        3.000000           6.600000          2.100000
7.7                        3.050000           6.600000          2.200000
7.9                        3.800000           6.400000          2.000000

In [41]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [49]:
iris_df["Mean"] = iris_df.mean(axis=1)

In [50]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

    Mean  
0  2.550  
1  2.375  
2  2.350  
3  2.350  
4  2.550

In [51]:
iris_df.drop(index=1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

      Mean  
0    2.550  
2    2.350  
3    2.350  
4    2.550  
5    2.850  
..     ...  
145  4.300  
146  3.925  
147  4.175  
148  4.325  
149  3.950  

[149 rows x 5 columns]

In [52]:
iris_df.drop(columns="sepal width (cm)", axis=1)

sepal length (cm)  petal length (cm)  petal width (cm)   Mean
0                  5.1                1.4               0.2  2.550
1                  4.9                1.4               0.2  2.375
2                  4.7                1.3               0.2  2.350
3                  4.6                1.5               0.2  2.350
4                  5.0                1.4               0.2  2.550
..                 ...                ...               ...    ...
145                6.7                5.2               2.3  4.300
146                6.3                5.0               1.9  3.925
147                6.5                5.2               2.0  4.175
148                6.2                5.4               2.3  4.325
149                5.9                5.1               1.8  3.950

[150 rows x 4 columns]

In [54]:
iris_df.loc[0:2, "sepal length (cm)"]

0    5.1
1    4.9
2    4.7
Name: sepal length (cm), dtype: float64

In [59]:
iris_df.iloc[:, 0:2]

sepal length (cm)  sepal width (cm)
0                  5.1               3.5
1                  4.9               3.0
2                  4.7               3.2
3                  4.6               3.1
4                  5.0               3.6
..                 ...               ...
145                6.7               3.0
146                6.3               2.5
147                6.5               3.0
148                6.2               3.4
149                5.9               3.0

[150 rows x 2 columns]

In [60]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

      Mean  
0    2.550  
1    2.375  
2    2.350  
3    2.350  
4    2.550  
..     ...  
145  4.300  
146  3.925  
147  4.175  
148  4.325  
149  3.950  

[150 rows x 5 columns]

In [61]:
iris_df.iloc[144: 146]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
144                6.7               3.3                5.7               2.5   
145                6.7               3.0                5.2               2.3   

     Mean  
144  4.55  
145  4.30

In [63]:
iris_df.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   
Mean                        0.940914         -0.223093           0.971379   

                   petal width (cm)      Mean  
sepal length (cm)          0.817941  0.940914  
sepal width (cm)          -0.366126 -0.223093  
petal length (cm)          0.962865  0.971379  
petal width (cm)           1.000000  0.953885  
Mean                       0.953885  1.000000