In [2]:
import numpy as np

In [3]:
matrix_1 = np.array([[1,2,3],[4,5,6]])
matrix_2 = np.array([[1,2],[3,4],[5,6]])

In [15]:
print(matrix_1)
print("----------")
print(matrix_2)

[[1 2 3]
 [4 5 6]]
----------
[[1 2]
 [3 4]
 [5 6]]


In [21]:
random_matrix = np.random.rand(2,2)
print(random_matrix)

[[0.50640595 0.78022237]
 [0.37513724 0.68986919]]


In [24]:
random_matrix_2 = np.random.randint(1, 60, (3, 3))
print(random_matrix_2)

[[33 44 16]
 [ 9 19 46]
 [ 4 55 54]]


In [26]:
matrix_with_ones = np.ones((3,3), dtype=int)
print(matrix_with_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [27]:
null_matrix = np.zeros((3,3), dtype=int)
print(null_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [30]:
identity_matrix = np.eye(5, dtype=int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [32]:
random_matrix_3 = np.random.randint(1, 101, (5, 5))
random_matrix_3_transpose = random_matrix_3.T
print(random_matrix_3)
print("----------")
print(random_matrix_3_transpose)

[[ 94  19   3  86  13]
 [ 54  54 100  68  64]
 [ 89  56  82  72  39]
 [ 68  63  11  52  16]
 [  3   3   3  53  88]]
----------
[[ 94  54  89  68   3]
 [ 19  54  56  63   3]
 [  3 100  82  11   3]
 [ 86  68  72  52  53]
 [ 13  64  39  16  88]]
